{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-curl-cronjob
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curl-container
              image: {{ .Values.cronjob.image }}
              args:
                - "-s"
                - "http://{{ .Release.Name }}-redcap-service.{{ .Release.Namespace }}.svc.cluster.local/redcap/cron.php"
          restartPolicy: OnFailure
{{- end }}