apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redcap-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # Use the local-path storage class for provisioning