apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redcap-edocs
  namespace:  {{ .Release.Namespace }}
  # annotations:
  #   "helm.sh/hook": pre-install
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # Use the local-path storage class for provisioning