apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.mariadb.auth.username | b64enc |quote }}
  password: {{ .Values.mariadb.auth.password | b64enc |quote }}