apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redcap-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: redcap
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: redcap
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  type: {{ .Values.service.type }}