{{- if .Values.adminer.enabled | default false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-adminer-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: adminer
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: adminer
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.adminer.servicePort }}
      targetPort: {{ .Values.adminer.containerPort }}
  type: ClusterIP
{{- end }}
